### ISSUE TITLE
player can walk vertically through objects

### ISSUE THREAD

**Issue by arellak** [arellak/TerrariaClone#10]

**Comment by ilimugur** [comment]
I'd like to work on this as part of Hacktoberfest, @arellak , that is, unless you started working on it already. I believe I've located the bug and I can have a fix ready within the hour.

**Comment by ilimugur** [comment]
While I have a candidate for a fix, I am curious to find out more about the details of the build process. I'm working on a Linux-based platform now, and it seems like `cmake CMakelists.txt` and `make all` produce an executable that displays an almost-empty map where I can't see any of the obstacles. (nor can I see the tiles for the "player") It's all black-and-white to me, so any help you may provide in clarifying the build procedure would be appreciated.
